#!/bin/sh
log="$1"
if [ ! -f "$log" ] ; then echo "$0: usage by-ipblock-usage LOGFILE[.gz]"; exit 2 ; fi
shift
logprint -f common --filter status=200 -c bytes,ip $log $@ |
    sed -e 's/[.][0-9]*$/.x/' |
    adder -n -b 1 -r 0 | sort -nrk 2
